use proc_macro2::TokenStream;
use quote::{quote, TokenStreamExt};
use rust_format::Formatter;

pub fn generate_file_content(file_tokens: TokenStream) -> Result<String, &'static str> {
    let mut tokens = quote!();

    let banner = r#"

// @generated by
//     __             _____     _                 ___ ___
//  _ |  |___ ___ ___|   __|___| |_ ___ _____  __| | |_  |
// | |_| |_ -| . |   |__   |  _|   | -_|     ||. |_  |  _|
// |_____|___|___|_|_|_____|___|_|_|___|_|_|_|___| |_|___|
//                                 -- www.JsonSchema42.org
"#
    .trim();

    tokens.append_all(file_tokens);

    let configuration = rust_format::Config::new_str().edition(rust_format::Edition::Rust2021);
    let formatter = rust_format::RustFmt::from_config(configuration);

    let content = formatter
        .format_tokens(tokens)
        .or(Err("error while formatting tokens"))?;

    Ok(format!("{}\n\n{}", banner, content))
}
